### PR TITLE
Filter out undefined query parameters and headers

### LINKED ISSUE #206: GET/HEAD requests: do not attach query parameter if value is `undefined`
Example

```js
const requestOptions = endpoint("GET /repos/{owner}/{repo}/contents/{path}", {
  owner: "owner",
  repo: "repo",
  path: "path/to/file.txt",
  ref: undefined,
});
```

`requestOptions.url` is now "https://api.github.com/repos/owner/repo/contents/path%2Fto%2Ffile.txt?ref=undefined", but should be just "https://api.github.com/repos/owner/repo/contents/path%2Fto%2Ffile.txt"

I'd appreciate a pull request if anyone would like to work on this. You can start out by creating a pull request with a failing test reproducing the above behavior. The test will go into [test/endpoint.test.ts](https://github.com/octokit/endpoint.js/blob/master/test/endpoint.test.ts).

### PR DESCRIPTION
**Pull request by frangio**
Fixes #206

I initially filtered out undefined query parameters in `add-query-parameters.ts`, but then I realized that undefined headers were also being erroneously included. To fix both of those I made it so that undefined values are removed from the options passed by the user before merging.

### CODE REVIEW

File: src/util/remove-undefined-properties.ts [hunk 1]
```diff
@@ -0,0 +1,9 @@
+export function removeUndefinedProperties(obj: any): any {
+  const copy = Object.assign({}, obj);
+  for (const key in copy) {
+    if (copy[key] === undefined) {
+      delete copy[key];
+    }
+  }
+  return copy;
+}
```
Comment (gr2m) [inline src/util/remove-undefined-properties.ts:9]: I'm a bit concerned about the performance implications here, the `endpoing.merge()` method gets called a lot. The `headers` object is already a copy via lowercaseKeys, so no need to create a new copy for that again.

Maybe remove the copy line from the method, and instead pass a copy into it when needed? Like this

```diff
- options = removeUndefinedProperties(options);
+ options = removeUndefinedProperties(Object.assign({}, options));
```

I'd also be curious to learn about the performance of creating a shallow copy and then removing undefined keys, vs creating a new object and only adding the properties to it that are not undefined. Could you maybe setup such a test? https://jsbench.me/ is good for this kind of test. I'd define two methods for the two startegies, and then test each twice: once with an object without any undefined properties, and once with some undefined properties

Comment (frangio) [reply src/util/remove-undefined-properties.ts:9]: The fastest option was to delete undefined properties from an existing object, so I'll switch to that approach. https://jsbench.me/78kfvy50sd/2

Comment (frangio) [reply src/util/remove-undefined-properties.ts:8]: Note that it's not exactly the same thing as in the benchmark because the lowercasing function is already doing a copy with undefined properties included. I didn't want to change that.

Comment (gr2m) [reply src/util/remove-undefined-properties.ts:8]: Thanks Francisco, this is great 👍🏼

**Review by gr2m — APPROVED** [review]
